baseURL = 'http://www.kinder-kaleidoskop.de/'
languageCode = 'de'
title = 'Kindertagespflege Kaleidoskop'
theme = 'ananke'
[params]
  body_classes = "sans-serif bg-near-white"
  text_color = "purple"
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
