baseURL = 'http://www.kinder-kaleidoskop.de/kaleidoskop/'
languageCode = 'de'
title = 'Kindertagespflege Kaleidoskop'
theme = 'ananke'
[params]
  body_classes = "abel-regular bg-light-gray"
  text_color = "darkgray"
  recent_posts_number = 0

