baseURL = 'http://www.kinder-kaleidoskop.de/'
languageCode = 'de'
title = 'Kindertagespflege Kaleidoskop'
theme = 'ananke'
[params]
  body_classes = "sans-serif bg-light-gray "
  text_color = "darkgray"
  recent_posts_number = 0